### ISSUE TITLE
Some file headers still say Apache Foundation

### ISSUE THREAD

**Issue by keilw** [microprofile/microprofile-config#10]
Some file headers e.g. Asciidoc still say
//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at

I think that is not correct. 
Should also say something like the .java files I assume. Apache License yes, but not under Apache Software Foundation, especially now that MP is an Eclipse project

**Comment by keilw** [comment]
Isn't this also completely addressed?

**Comment by keilw** [comment]
Not yet, my PR https://github.com/microprofile/microprofile-config/pull/12 addressed the last spot in the README file. So this could be closed if the PR was merged.

**Comment by Emily-Jiang** [comment]
I think this issue is solved. Reopen if it is not the case.

**Comment by keilw** [comment]
Yes it looks like. Thanks. I did not edit classes as of now (depending on package name requirements by Eclipse this may change more drastically) but as the history of `Config` shows @author Mark was added after a push saying "updated based on Mark's comments" (he did not file a PR or push anything directly then either) I'd appreciate credits for https://github.com/microprofile/microprofile-config/issues/7 in that class if possible ;-)

**Comment by Emily-Jiang** [comment]
ok. Please create a pr to get your name mentioned.

**Comment by keilw** [comment]
Done: https://github.com/microprofile/microprofile-config/pull/33

**Comment by struberg** [comment]
To set things straight. I was added as @author because I wrote it. Simply as that! Dmitry copied it from me for his JavaOne slide and Emily took it from the slides. 
I have not checked what you actually contributed, but in any can only state that from a legal perspective it requires a certain level of originary work to constitute intellectual property rights (which is required to claim authorship).
In other words: no serious amount of originary work -> no @author.
And that's not my personal interpretation, that is established IP law.

So if you really added some substantial contributions then I'm all for adding you as @author. If it was only random name changes and polishing docs then I'm -1. 
Oh, writing substantial portions of documentation of course also constitutes own IP. But again, simple reformatting or minor rewording does NOT.
